version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: web
    volumes:
      - ../:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app
    volumes:
      - ../:/var/www
    links:
      - db
    environment:
      - DB_PORT=3306
      - DB_HOST=db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=books
      - MYSQL_ROOT_PASSWORD=books
      - MYSQL_USER=books
      - MYSQL_PASSWORD=books
    ports:
        - "13306:3306"
    volumes:
    - "./data/db/mysql:/var/lib/mysql"